spring.application.name: order-service

server.port: 8085

security:
  basic:
    enabled: false
spring.oauth2:
  client:
    clientId: order-service
    clientSecret: secret
    accessTokenUri: http://localhost:8080/uaa/oauth/token
    
  resource:
    id: order
    jwt.keyUri: ${targets.uaa}/token_key
    userInfoUri: ${targets.uaa}/userinfo

spring.jpa.hibernate.ddl-auto: update